import type { CSSProperties } from 'react'

export const editableRootStyle = {
  // "Playful directory" system: warm cream paper background, sage/olive
  // muted accent, terracotta primary accent, deep espresso text. Chunky,
  // friendly, pill-shaped — built for a freelancer/business directory feel.
  '--slot4-page-bg': '#F7F1DE',
  '--slot4-page-text': '#4E220F',
  '--slot4-panel-bg': '#EFE6CC',
  '--slot4-surface-bg': '#FFFCF3',
  '--slot4-muted-text': '#7A5B44',
  '--slot4-soft-muted-text': '#96775F',
  '--slot4-accent': '#9D6638',
  '--slot4-accent-fill': '#9D6638',
  '--slot4-accent-soft': '#EDE6D2',
  '--slot4-on-accent': '#FDF8EC',
  '--slot4-dark-bg': '#4E220F',
  '--slot4-dark-text': '#F7F1DE',
  '--slot4-media-bg': '#E7DFC4',
  '--slot4-cream': '#F7F1DE',
  '--slot4-warm': '#EFE6CC',
  '--slot4-lavender': '#DEE3CE',
  '--slot4-gray': '#EFE6CC',
  '--slot4-sage': '#B0BA99',
  '--slot4-sage-soft': '#E4E7DA',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#F7F1DE',
  '--editable-page-text': '#4E220F',
  '--editable-container': '1400px',
  '--editable-border': '#E1D6B5',
  '--editable-nav-bg': '#F7F1DE',
  '--editable-nav-text': '#4E220F',
  '--editable-nav-active': '#9D6638',
  '--editable-nav-active-text': '#FDF8EC',
  '--editable-cta-bg': '#9D6638',
  '--editable-cta-text': '#FDF8EC',
  '--editable-search-bg': '#FFFCF3',
  '--editable-footer-bg': '#F1E9D2',
  '--editable-footer-text': '#4E220F',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  sageBg: 'bg-[var(--slot4-sage)]',
  sageSoftBg: 'bg-[var(--slot4-sage-soft)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_2px_10px_rgba(78,34,15,0.08)]',
  shadowStrong: 'shadow-[0_14px_36px_rgba(78,34,15,0.16)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(78,34,15,0.02),rgba(78,34,15,0.78))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-bold uppercase tracking-[0.24em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-extrabold leading-[1.05] tracking-[-0.01em] sm:text-5xl lg:text-[3.25rem]',
    sectionTitle: 'text-3xl font-extrabold tracking-[-0.01em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-2xl border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-2xl border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-2xl ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[linear-gradient(135deg,var(--slot4-accent)_0%,#C08A55_100%)] px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-on-accent)] shadow-[0_8px_20px_rgba(157,102,56,0.28)] transition duration-300 hover:-translate-y-0.5 hover:shadow-[0_12px_26px_rgba(157,102,56,0.36)] active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border-2 border-[var(--slot4-sage)] bg-transparent px-6 py-3 text-sm font-bold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-300 hover:-translate-y-0.5 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:shadow-[0_10px_24px_rgba(157,102,56,0.3)] active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-2xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_16px_36px_rgba(78,34,15,0.18)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
